export const PartiesFacetABI = [
  {
    type: "event",
    anonymous: false,
    name: "PartyDeactivated",
    inputs: [
      {
        type: "tuple",
        name: "party",
        indexed: true,
        components: [
          { type: "string", name: "name" },
          { type: "address", name: "addr" },
          { type: "uint8", name: "role" },
          { type: "bool", name: "active" },
          { type: "bool", name: "frozen" },
          { type: "uint8", name: "rating" },
        ],
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PartyRegistered",
    inputs: [
      {
        type: "tuple",
        name: "party",
        indexed: true,
        components: [
          { type: "string", name: "name" },
          { type: "address", name: "addr" },
          { type: "uint8", name: "role" },
          { type: "bool", name: "active" },
          { type: "bool", name: "frozen" },
          { type: "uint8", name: "rating" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "deactivateParty",
    constant: false,
    payable: false,
    inputs: [{ type: "uint8", name: "_role" }],
    outputs: [],
  },
  {
    type: "function",
    name: "freezeParty",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getActiveParties",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [
      {
        type: "tuple[]",
        name: "",
        components: [
          { type: "string", name: "name" },
          { type: "address", name: "addr" },
          { type: "uint8", name: "role" },
          { type: "bool", name: "active" },
          { type: "bool", name: "frozen" },
          { type: "uint8", name: "rating" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getActivePartiesAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [{ type: "address[]", name: "" }],
  },
  {
    type: "function",
    name: "getActivePartiesAddressByRole",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint8", name: "_role" }],
    outputs: [{ type: "address[]", name: "" }],
  },
  {
    type: "function",
    name: "getActivePartiesByRole",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "uint8", name: "_role" }],
    outputs: [
      {
        type: "tuple[]",
        name: "",
        components: [
          { type: "string", name: "name" },
          { type: "address", name: "addr" },
          { type: "uint8", name: "role" },
          { type: "bool", name: "active" },
          { type: "bool", name: "frozen" },
          { type: "uint8", name: "rating" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getParty",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [
      {
        type: "tuple",
        name: "",
        components: [
          { type: "string", name: "name" },
          { type: "address", name: "addr" },
          { type: "uint8", name: "role" },
          { type: "bool", name: "active" },
          { type: "bool", name: "frozen" },
          { type: "uint8", name: "rating" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "hasActiveRole",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      { type: "address", name: "_addr" },
      { type: "uint8", name: "_role" },
    ],
    outputs: [{ type: "bool", name: "" }],
  },
  {
    type: "function",
    name: "registerParty",
    constant: false,
    payable: false,
    inputs: [
      { type: "string", name: "_name" },
      { type: "uint8", name: "_role" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "unfreezeParty",
    constant: false,
    payable: false,
    inputs: [{ type: "address", name: "_addr" }],
    outputs: [],
  },
];
